name: Release Please

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Release Please Action
        uses: googleapis/release-please-action@v4
        with:
          release-type: simple
          package-name: R3M.StartupManager
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
